const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Pin,
		C3.Plugins.Mouse,
		C3.Plugins.TextBox,
		C3.Plugins.Text,
		C3.Plugins.Shape3D,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.TextBox.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.Sprite.Cnds.IsOverlapping
	];
};
self.C3_JsPropNameTable = [
	{ArrastrarYSoltar: 0},
	{ATX_Case: 0},
	{Pegado: 0},
	{cpu: 0},
	{cpu_cooler: 0},
	{Grafica: 0},
	{Pegado2: 0},
	{PlacaBase: 0},
	{psu: 0},
	{ram: 0},
	{Mouse: 0},
	{EntradaDeTextoPlacaBase: 0},
	{Texto2: 0},
	{Variable1: 0},
	{Aciertos: 0},
	{Texto3: 0},
	{EntradaDeTextopsu: 0},
	{EntradaDeTextoRAM: 0},
	{EntradaDeTexto_CPU_COOLER: 0},
	{EntradaDeTexto_CPU: 0},
	{EntradaDeTexto_grafica: 0},
	{Forma3D: 0},
	{ComprobadorPlacaBase: 0},
	{ComprobadorPsu: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Texto: 0},
	{Texto4: 0},
	{Texto5: 0}
];

self.InstanceType = {
	ATX_Case: class extends self.ISpriteInstance {},
	cpu: class extends self.ISpriteInstance {},
	cpu_cooler: class extends self.ISpriteInstance {},
	Grafica: class extends self.ISpriteInstance {},
	PlacaBase: class extends self.ISpriteInstance {},
	psu: class extends self.ISpriteInstance {},
	ram: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	EntradaDeTextoPlacaBase: class extends self.ITextInputInstance {},
	Texto2: class extends self.ITextInstance {},
	Aciertos: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	EntradaDeTextopsu: class extends self.ITextInputInstance {},
	EntradaDeTextoRAM: class extends self.ITextInputInstance {},
	EntradaDeTexto_CPU_COOLER: class extends self.ITextInputInstance {},
	EntradaDeTexto_CPU: class extends self.ITextInputInstance {},
	EntradaDeTexto_grafica: class extends self.ITextInputInstance {},
	Forma3D: class extends self.I3DShapeInstance {},
	ComprobadorPlacaBase: class extends self.ISpriteInstance {},
	ComprobadorPsu: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Texto4: class extends self.ITextInstance {},
	Texto5: class extends self.ITextInstance {}
}